/**
 * gen-seed-sql.ts
 * files/ 配下のプリセット JSON を読み、D1 用 INSERT 文を migrations/seed_presets.sql に書き出す。
 * Usage: pnpm db:seed:gen   (または npx tsx scripts/gen-seed-sql.ts)
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { randomUUID } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface PresetQuestion { text: string; options: string[]; correctIndex: number; timeLimitSec: number; }
interface PresetGame { scene: string; title: string; mode: 'trivia' | 'polling' | 'opinion'; loseRule?: 'minority' | 'majority'; description: string; questions: PresetQuestion[]; }

function generateJoinCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  return Array.from({ length: 6 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
}
function sql(v: string): string { return "'" + v.replace(/'/g, "''") + "'"; }

function loadPresetsFromDir(dirPath: string, sceneOverride?: string): PresetGame[] {
  const result: PresetGame[] = [];
  for (const f of readdirSync(dirPath).filter(x => x.endsWith('.json'))) {
    const data = JSON.parse(readFileSync(join(dirPath, f), 'utf-8'));
    const arr: PresetGame[] = (Array.isArray(data) ? data : [data])
      .filter((it: unknown) => it !== null && typeof it === 'object' && !Array.isArray(it) && (it as PresetGame).questions !== undefined);
    if (sceneOverride) arr.forEach(p => { p.scene = sceneOverride; });
    result.push(...arr);
  }
  return result;
}

function main() {
  const presets: PresetGame[] = [];
  for (const f of ['../files/partyrant_presets.json', '../files/partyrant_majority_quiz_pack.json']) {
    presets.push(...(JSON.parse(readFileSync(join(__dirname, f), 'utf-8')) as PresetGame[]));
  }
  for (const d of ['../files/0420/partyrant_quizzes', '../files/0420/partyrant_quizzes_vol2', '../files/0420/partyrant_trivia_quizzes', '../files/0420b/partyrant_ultimate_choices']) {
    presets.push(...loadPresetsFromDir(join(__dirname, d)));
  }
  presets.push(...loadPresetsFromDir(join(__dirname, '../files/0421/partyrant_who_is'), 'この中で●●なのは誰だ'));
  presets.push(...loadPresetsFromDir(join(__dirname, '../files/0422/partyrant_cast'), 'キャスト指名'));

  const now = Date.now();
  const lines: string[] = ['-- generated by gen-seed-sql.ts', 'PRAGMA foreign_keys = ON;', 'delete from games where is_preset = 1;'];
  for (const p of presets) {
    const id = randomUUID();
    const questions = JSON.stringify(p.questions.map((q, i) => ({
      id: randomUUID(), text: q.text, options: q.options, correctIndex: q.correctIndex, timeLimitSec: q.timeLimitSec, orderIndex: i,
    })));
    lines.push(
      `insert into games (id, event_id, host_id, join_code, mode, game_mode, lose_rule, title, description, scene, is_preset, questions, status, current_question_index, current_question_started_at, created_at, ended_at) values (` +
      `${sql(id)}, NULL, NULL, ${sql(generateJoinCode())}, ${sql(p.mode)}, 'live', ${p.loseRule ? sql(p.loseRule) : 'NULL'}, ${sql(p.title)}, ${sql(p.description)}, ${sql(p.scene)}, 1, ${sql(questions)}, 'draft', 0, NULL, ${now}, NULL);`
    );
  }
  const out = join(__dirname, '../migrations/seed_presets.sql');
  writeFileSync(out, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${presets.length} presets to ${out}`);
}
main();
